feat: always check all filer

diff --git a/.github/workflows/check_json_validity.yaml b/.github/workflows/check_json_validity.yaml
--- a/.github/workflows/check_json_validity.yaml
+++ b/.github/workflows/check_json_validity.yaml
@@ -19,21 +19,25 @@ jobs:
       - name: Install jq
         run: |
           sudo apt update && sudo apt install jq
-      - name: Check JSON-LD files
+      - name: Check JSON and JSON-LD files
         run: |
           error=0
+          echo "Checking JSON-LD files"
           for file in $(find . -name "*.jsonld"); do
             printf "Checking $file .. "
             jq empty $file && echo "OK" || { error=1; echo "KO invalid JSON"; }
+          done
+          echo ""
+          echo "Checking JSON files"
+          for file in $(find . -name "*.json"); do
+            printf "Checking $file .. "
+            jq empty $file && echo "OK" || { error=1; echo "*** KO invalid JSON ***"; }
           done
           exit $error
         shell: bash
       - name: Check JSON files
         run: |
           error=0
-          for file in $(find . -name "*.json"); do
-            printf "Checking $file .. "
-            jq empty $file && echo "OK" || { error=1; echo "KO invalid JSON"; }
-          done
+
           exit $error
         shell: bash
